# Generated by Django 3.2.11 on 2022-02-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_app', '0002_auto_20220210_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
    ]
