# Generated by Django 3.2.11 on 2022-01-18 11:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="contact_number",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
